/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    brands: Brand;
    trainers: Trainer;
    courses: Course;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    trainers: TrainersSelect<false> | TrainersSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    homepage: Homepage;
    footer: Footer;
    branding: Branding;
    'seo-settings': SeoSetting;
    pricing: Pricing;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    branding: BrandingSelect<false> | BrandingSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('admin' | 'trainer' | 'brand') | null;
  subscriptionTier?: ('basis' | 'medium' | 'premium') | null;
  subscriptionStatus?: ('active' | 'inactive' | 'canceled' | 'past_due') | null;
  /**
   * Stripe Customer ID (auto-ingevuld)
   */
  stripeCustomerId?: string | null;
  /**
   * Stripe Subscription ID (auto-ingevuld)
   */
  stripeSubscriptionId?: string | null;
  /**
   * Vervaldatum abonnement
   */
  subscriptionExpiresAt?: string | null;
  /**
   * Mollie Customer ID (auto-ingevuld)
   */
  mollieCustomerId?: string | null;
  /**
   * Mollie Subscription ID (auto-ingevuld)
   */
  mollieSubscriptionId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Geüpload door
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  /**
   * Laat leeg voor hoofdcategorie
   */
  parent?: (number | null) | Category;
  description?: string | null;
  icon?: (number | null) | Media;
  /**
   * Teksten voor de publieke categoriepagina (/opleidingen/[slug]).
   */
  landing?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    h1?: string | null;
    heroIntro?: string | null;
    seoIntro?: string | null;
    sectionTitle?: string | null;
    sectionBody?: string | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  /**
   * Brand gebruikersaccount
   */
  owner: number | User;
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  website?: string | null;
  email?: string | null;
  phone?: string | null;
  tags?: ('belgisch' | 'vegan' | 'natuurlijk' | 'professioneel' | 'biologisch' | 'duurzaam' | 'luxe')[] | null;
  /**
   * Geverifieerd door Blissify
   */
  verified?: boolean | null;
  featured?: boolean | null;
  /**
   * Zoekmachine-optimalisatie instellingen
   */
  seo?: {
    /**
     * Paginatitel voor zoekmachines (max 60 tekens). Laat leeg om de naam/titel te gebruiken.
     */
    title?: string | null;
    /**
     * Beschrijving voor zoekmachines (max 160 tekens).
     */
    description?: string | null;
    /**
     * Het hoofdzoekwoord waarop je wilt scoren (bijv. "gelnagels opleiding Antwerpen")
     */
    focusKeyphrase?: string | null;
    /**
     * Open Graph afbeelding voor Facebook/LinkedIn sharing (1200x630px). Laat leeg voor de standaard.
     */
    ogImage?: (number | null) | Media;
    /**
     * Vink aan om deze pagina uit zoekresultaten te houden.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainers".
 */
export interface Trainer {
  id: number;
  displayName: string;
  slug: string;
  /**
   * Trainer gebruikersaccount
   */
  owner: number | User;
  /**
   * Gekoppeld aan brand (optioneel)
   */
  brand?: (number | null) | Brand;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specializations?:
    | (
        | 'massage'
        | 'nagelstyliste'
        | 'schoonheid'
        | 'yoga'
        | 'voeding'
        | 'aromatherapie'
        | 'reiki'
        | 'mindfulness'
        | 'holistische-therapie'
        | 'persoonlijke-ontwikkeling'
      )[]
    | null;
  location?: {
    city?: string | null;
    province?: string | null;
    online?: boolean | null;
  };
  website?: string | null;
  email?: string | null;
  phone?: string | null;
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    linkedin?: string | null;
  };
  verified?: boolean | null;
  featured?: boolean | null;
  /**
   * Zoekmachine-optimalisatie instellingen
   */
  seo?: {
    /**
     * Paginatitel voor zoekmachines (max 60 tekens). Laat leeg om de naam/titel te gebruiken.
     */
    title?: string | null;
    /**
     * Beschrijving voor zoekmachines (max 160 tekens).
     */
    description?: string | null;
    /**
     * Het hoofdzoekwoord waarop je wilt scoren (bijv. "gelnagels opleiding Antwerpen")
     */
    focusKeyphrase?: string | null;
    /**
     * Open Graph afbeelding voor Facebook/LinkedIn sharing (1200x630px). Laat leeg voor de standaard.
     */
    ogImage?: (number | null) | Media;
    /**
     * Vink aan om deze pagina uit zoekresultaten te houden.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published' | 'archived';
  /**
   * Uitgelicht in de directory
   */
  featured?: boolean | null;
  featuredPosition?: ('top' | 'permanent_top') | null;
  /**
   * Trainer die de opleiding geeft
   */
  trainer?: (number | null) | Trainer;
  /**
   * Brand die de opleiding publiceert
   */
  brand?: (number | null) | Brand;
  category: number | Category;
  coverImage?: (number | null) | Media;
  /**
   * Korte samenvatting (max 200 tekens)
   */
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  format?: ('online' | 'fysiek' | 'hybride')[] | null;
  location?: {
    address?: string | null;
    city?: string | null;
    province?: string | null;
    postcode?: string | null;
  };
  duration?: {
    value?: number | null;
    unit?: ('hours' | 'days' | 'weeks' | 'months') | null;
  };
  price?: {
    amount?: number | null;
    currency?: 'EUR' | null;
    isFree?: boolean | null;
    priceOnRequest?: boolean | null;
  };
  language?: ('nl' | 'fr' | 'en')[] | null;
  level?: ('beginner' | 'gevorderd' | 'expert' | 'all') | null;
  certificate?: boolean | null;
  accreditation?: string | null;
  /**
   * URL naar de inschrijvingspagina op de externe website
   */
  externalUrl: string;
  startDates?:
    | {
        date: string;
        spotsAvailable?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Vrije trefwoorden voor zoeken
   */
  tags?: string[] | null;
  /**
   * Zoekmachine-optimalisatie instellingen
   */
  seo?: {
    /**
     * Paginatitel voor zoekmachines (max 60 tekens). Laat leeg om de naam/titel te gebruiken.
     */
    title?: string | null;
    /**
     * Beschrijving voor zoekmachines (max 160 tekens).
     */
    description?: string | null;
    /**
     * Het hoofdzoekwoord waarop je wilt scoren (bijv. "gelnagels opleiding Antwerpen")
     */
    focusKeyphrase?: string | null;
    /**
     * Open Graph afbeelding voor Facebook/LinkedIn sharing (1200x630px). Laat leeg voor de standaard.
     */
    ogImage?: (number | null) | Media;
    /**
     * Vink aan om deze pagina uit zoekresultaten te houden.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    image?: (number | null) | Media;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  blocks?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            items?:
              | {
                  /**
                   * Tabler-klasse, bijv. ti ti-target-arrow
                   */
                  icon?: string | null;
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            quote: string;
            author?: string | null;
            company?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial';
          }
        | {
            title: string;
            body?: string | null;
            buttonLabel?: string | null;
            buttonUrl?: string | null;
            background?: ('forest' | 'chalk') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            items?:
              | {
                  logo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logos';
          }
        | {
            items?:
              | {
                  name: string;
                  price: string;
                  period?: string | null;
                  features?:
                    | {
                        feature?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  recommended?: boolean | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingTiers';
          }
        | {
            col1?: string | null;
            col2?: string | null;
            col3?: string | null;
            rows?:
              | {
                  feature: string;
                  v1?: string | null;
                  v2?: string | null;
                  v3?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparison';
          }
        | {
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
      )[]
    | null;
  /**
   * Zoekmachine-optimalisatie instellingen
   */
  seo?: {
    /**
     * Paginatitel voor zoekmachines (max 60 tekens). Laat leeg om de naam/titel te gebruiken.
     */
    title?: string | null;
    /**
     * Beschrijving voor zoekmachines (max 160 tekens).
     */
    description?: string | null;
    /**
     * Het hoofdzoekwoord waarop je wilt scoren (bijv. "gelnagels opleiding Antwerpen")
     */
    focusKeyphrase?: string | null;
    /**
     * Open Graph afbeelding voor Facebook/LinkedIn sharing (1200x630px). Laat leeg voor de standaard.
     */
    ogImage?: (number | null) | Media;
    /**
     * Vink aan om deze pagina uit zoekresultaten te houden.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'trainers';
        value: number | Trainer;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  subscriptionTier?: T;
  subscriptionStatus?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  subscriptionExpiresAt?: T;
  mollieCustomerId?: T;
  mollieSubscriptionId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  icon?: T;
  landing?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        h1?: T;
        heroIntro?: T;
        seoIntro?: T;
        sectionTitle?: T;
        sectionBody?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  owner?: T;
  logo?: T;
  coverImage?: T;
  description?: T;
  website?: T;
  email?: T;
  phone?: T;
  tags?: T;
  verified?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyphrase?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainers_select".
 */
export interface TrainersSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  owner?: T;
  brand?: T;
  photo?: T;
  bio?: T;
  specializations?: T;
  location?:
    | T
    | {
        city?: T;
        province?: T;
        online?: T;
      };
  website?: T;
  email?: T;
  phone?: T;
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        linkedin?: T;
      };
  verified?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyphrase?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  featured?: T;
  featuredPosition?: T;
  trainer?: T;
  brand?: T;
  category?: T;
  coverImage?: T;
  shortDescription?: T;
  description?: T;
  format?: T;
  location?:
    | T
    | {
        address?: T;
        city?: T;
        province?: T;
        postcode?: T;
      };
  duration?:
    | T
    | {
        value?: T;
        unit?: T;
      };
  price?:
    | T
    | {
        amount?: T;
        currency?: T;
        isFree?: T;
        priceOnRequest?: T;
      };
  language?: T;
  level?: T;
  certificate?: T;
  accreditation?: T;
  externalUrl?: T;
  startDates?:
    | T
    | {
        date?: T;
        spotsAvailable?: T;
        id?: T;
      };
  tags?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyphrase?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        image?: T;
        ctaLabel?: T;
        ctaUrl?: T;
      };
  blocks?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonial?:
          | T
          | {
              quote?: T;
              author?: T;
              company?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        logos?:
          | T
          | {
              items?:
                | T
                | {
                    logo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricingTiers?:
          | T
          | {
              items?:
                | T
                | {
                    name?: T;
                    price?: T;
                    period?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    recommended?: T;
                    ctaLabel?: T;
                    ctaUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        comparison?:
          | T
          | {
              col1?: T;
              col2?: T;
              col3?: T;
              rows?:
                | T
                | {
                    feature?: T;
                    v1?: T;
                    v2?: T;
                    v3?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyphrase?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  logo?: (number | null) | Media;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    badge?: string | null;
    title?: string | null;
    /**
     * Het woord met terracotta-gradient.
     */
    highlight?: string | null;
    subtitle?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaUrl?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaUrl?: string | null;
  };
  trustText?: string | null;
  why?: {
    eyebrow?: string | null;
    title?: string | null;
    cards?:
      | {
          /**
           * Tabler-klasse, bijv. ti ti-rosette-discount-check
           */
          icon?: string | null;
          title: string;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  photoSection?: {
    title?: string | null;
    subtitle?: string | null;
    tiles?:
      | {
          title: string;
          body?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialInstagram?: string | null;
  socialFacebook?: string | null;
  newsletterTitle?: string | null;
  newsletterSubtitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: number;
  siteName: string;
  tagline?: string | null;
  /**
   * Aanbevolen: SVG of PNG met transparante achtergrond
   */
  logo?: (number | null) | Media;
  /**
   * Lichte versie van het logo (voor donkere achtergronden)
   */
  logoLight?: (number | null) | Media;
  /**
   * Favicon - 32x32px of 64x64px
   */
  favicon?: (number | null) | Media;
  colors?: {
    /**
     * Primaire kleur (hex)
     */
    primary?: string | null;
    /**
     * Tekst op primaire kleur (hex)
     */
    primaryForeground?: string | null;
    /**
     * Secundaire kleur (hex)
     */
    secondary?: string | null;
    /**
     * Accentkleur (hex)
     */
    accent?: string | null;
    /**
     * Achtergrondkleur (hex)
     */
    background?: string | null;
  };
  fonts?: {
    /**
     * Lettertype voor titels
     */
    heading?: ('playfair-display' | 'cormorant-garamond' | 'lora' | 'libre-baskerville') | null;
    /**
     * Lettertype voor bodytekst
     */
    body?: ('inter' | 'dm-sans' | 'nunito' | 'lato') | null;
  };
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    linkedin?: string | null;
    tiktok?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    kvk?: string | null;
    btw?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: number;
  /**
   * Fallback paginatitel als er geen specifieke is ingesteld
   */
  defaultTitle: string;
  /**
   * Template voor paginatitels. Gebruik %s voor de paginanaam.
   */
  titleTemplate?: string | null;
  /**
   * Fallback meta description (max 160 tekens)
   */
  defaultDescription?: string | null;
  /**
   * Standaard Open Graph afbeelding (1200x630px) voor social sharing
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * @handle zonder @
   */
  twitterHandle?: string | null;
  /**
   * Google Search Console verificatiecode
   */
  googleVerification?: string | null;
  /**
   * Zet de hele site op noindex (alleen voor staging/dev)
   */
  noindex?: boolean | null;
  structuredData?: {
    organizationName?: string | null;
    organizationUrl?: string | null;
    organizationType?: ('Organization' | 'LocalBusiness' | 'EducationalOrganization') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  intro?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
  };
  tiers?:
    | {
        /**
         * Stabiele sleutel: basis / medium / premium
         */
        key: string;
        name: string;
        tagline?: string | null;
        price: string;
        period?: string | null;
        desc?: string | null;
        recommended?: boolean | null;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  comparison?: {
    col1?: string | null;
    col2?: string | null;
    col3?: string | null;
    rows?:
      | {
          feature: string;
          v1?: string | null;
          v2?: string | null;
          v3?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  bottomCta?: {
    title?: string | null;
    body?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  logo?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        highlight?: T;
        subtitle?: T;
        primaryCtaLabel?: T;
        primaryCtaUrl?: T;
        secondaryCtaLabel?: T;
        secondaryCtaUrl?: T;
      };
  trustText?: T;
  why?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  photoSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        tiles?:
          | T
          | {
              title?: T;
              body?: T;
              image?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  socialInstagram?: T;
  socialFacebook?: T;
  newsletterTitle?: T;
  newsletterSubtitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding_select".
 */
export interface BrandingSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  logoLight?: T;
  favicon?: T;
  colors?:
    | T
    | {
        primary?: T;
        primaryForeground?: T;
        secondary?: T;
        accent?: T;
        background?: T;
      };
  fonts?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        linkedin?: T;
        tiktok?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        kvk?: T;
        btw?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultOgImage?: T;
  twitterHandle?: T;
  googleVerification?: T;
  noindex?: T;
  structuredData?:
    | T
    | {
        organizationName?: T;
        organizationUrl?: T;
        organizationType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
      };
  tiers?:
    | T
    | {
        key?: T;
        name?: T;
        tagline?: T;
        price?: T;
        period?: T;
        desc?: T;
        recommended?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        id?: T;
      };
  comparison?:
    | T
    | {
        col1?: T;
        col2?: T;
        col3?: T;
        rows?:
          | T
          | {
              feature?: T;
              v1?: T;
              v2?: T;
              v3?: T;
              id?: T;
            };
      };
  bottomCta?:
    | T
    | {
        title?: T;
        body?: T;
        buttonLabel?: T;
        buttonUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}